import { TenseSummary } from '../interfaces/tense-summary.interface';

/** Catalogue in default order (same as `TENSE_IDS`). */
export const TENSE_CATALOGUE: readonly TenseSummary[] = [
  {
    id: 'presente',
    name: 'Presente',
    hint: 'зазвичай, факти',
    exampleYo: 'hablo',
    when: 'Зазвичай, завжди, факти',
    english: 'Present Simple',
    markers: ['siempre', 'cada día', 'normalmente'],
  },
  {
    id: 'estar-gerundio',
    name: 'Estar + gerundio',
    hint: 'просто зараз',
    exampleYo: 'estoy hablando',
    when: 'Просто зараз, у процесі',
    english: 'Present Continuous',
    markers: ['ahora', 'en este momento'],
  },
  {
    id: 'ir-a-infinitivo',
    name: 'Ir a + infinitivo',
    hint: 'плани, «збираюся»',
    exampleYo: 'voy a hablar',
    when: 'Плани, найближче майбутнє',
    english: 'be going to',
    markers: ['mañana', 'esta noche', 'el próximo mes'],
  },
  {
    id: 'preterito-perfecto',
    name: 'Pretérito perfecto',
    hint: 'минуле, пов’язане із «зараз»',
    exampleYo: 'he hablado',
    when: 'Минуле, пов’язане із «зараз»; досвід',
    english: 'Present Perfect',
    markers: ['hoy', 'esta semana', 'ya', 'todavía no', 'nunca'],
  },
  {
    id: 'preterito-indefinido',
    name: 'Pretérito indefinido',
    hint: 'закрите минуле',
    exampleYo: 'hablé',
    when: 'Закрите минуле, конкретний момент',
    english: 'Past Simple',
    markers: ['ayer', 'el lunes', 'en 2020', 'la semana pasada'],
  },
  {
    id: 'preterito-imperfecto',
    name: 'Pretérito imperfecto',
    hint: 'звички й опис у минулому',
    exampleYo: 'hablaba',
    when: 'Звички, опис, тло подій у минулому',
    english: 'used to / Past Continuous',
    markers: ['antes', 'siempre', 'de niño', 'mientras'],
  },
  {
    id: 'preterito-pluscuamperfecto',
    name: 'Pretérito pluscuamperfecto',
    hint: 'минуле до минулого',
    exampleYo: 'había hablado',
    when: 'Дія, що сталася раніше за іншу минулу',
    english: 'Past Perfect',
    markers: ['ya', 'antes', 'todavía no', 'cuando llegué'],
  },
  {
    id: 'futuro-simple',
    name: 'Futuro simple',
    hint: 'майбутнє, прогнози',
    exampleYo: 'hablaré',
    when: 'Майбутнє, прогнози, обіцянки, здогадки',
    english: 'will',
    markers: ['mañana', 'el año que viene', 'algún día', 'pronto'],
  },
  {
    id: 'futuro-perfecto',
    name: 'Futuro perfecto',
    hint: 'буде зроблено до…',
    exampleYo: 'habré hablado',
    when: 'Дія завершиться до моменту в майбутньому',
    english: 'will have done',
    markers: ['para mañana', 'para entonces', 'dentro de un año'],
  },
  {
    id: 'condicional-simple',
    name: 'Condicional simple',
    hint: '«би», ввічливість',
    exampleYo: 'hablaría',
    when: '«Би»: гіпотеза, ввічливість, порада',
    english: 'would',
    markers: [],
  },
  {
    id: 'condicional-compuesto',
    name: 'Condicional compuesto',
    hint: '«зробив би» в минулому',
    exampleYo: 'habría hablado',
    when: 'Нереалізована гіпотеза в минулому',
    english: 'would have done',
    markers: ['en tu lugar', 'yo que tú'],
  },
  {
    id: 'imperativo',
    name: 'Imperativo',
    hint: 'накази, прохання',
    exampleYo: 'habla (tú)',
    when: 'Накази, прохання, інструкції, поради',
    english: 'Imperative',
    markers: ['por favor'],
  },
  {
    id: 'presente-subjuntivo',
    name: 'Presente de subjuntivo',
    hint: 'бажання, сумнів, емоції',
    exampleYo: 'hable',
    when: 'Бажання, сумнів, емоції, оцінка після «que»',
    english: '— (that he go; I want you to go)',
    markers: ['quiero que', 'ojalá', 'es importante que', 'cuando + майбутнє'],
  },
  {
    id: 'imperfecto-subjuntivo',
    name: 'Imperfecto de subjuntivo',
    hint: '«якби…», минуле бажання',
    exampleYo: 'hablara / hablase',
    when: '«Якби…», бажання та сумнів у минулому',
    english: 'if I were / if I did',
    markers: ['si', 'ojalá', 'como si', 'quería que'],
  },
];
